/**
 * Copyright (c) 2026 b1zya (https://github.com/b1zya/patchright-cli).
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Regenerates scripts/upstream-snapshot/client.patch: the diff between the pristine
// upstream client (vendor/cli-client) and our layer (src), file by file. Like patchright's
// own patchright.patch it is documentation, not an input: the layer is applied by three-way
// merge, this file only makes it readable in reviews.
//
//   tsx scripts/upstream-patch.ts [--check]   (--check exits 1 when the file is stale)

import { spawnSync } from 'child_process';
import fs from 'fs';

import { clientPatchFile, forkedFiles, lf, readVersions, root } from './upstream/lib';

export function renderClientPatch(): string {
  const versions = readVersions();
  const parts = [
    `# Our client layer relative to the pristine upstream client (Playwright ${versions.patchrightCore.playwrightTag},`,
    `# compiled as patchright-core ${versions.patchrightCore.version}). Generated by scripts/upstream-patch.ts;`,
    '# not applied anywhere: the layer is carried forward by three-way merge in scripts/roll.ts.',
    '',
  ];
  for (const file of forkedFiles) {
    const result = spawnSync('git', ['diff', '--no-index', '--minimal', '--', file.vendor, file.ours], { cwd: root, encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 });
    if (result.error)
      throw result.error;
    parts.push(lf(result.stdout));
  }
  return parts.join('\n');
}

export function regenerateClientPatch(): void {
  fs.writeFileSync(clientPatchFile, renderClientPatch());
}

if (require.main === module) {
  const next = renderClientPatch();
  const current = fs.existsSync(clientPatchFile) ? lf(fs.readFileSync(clientPatchFile, 'utf8')) : undefined;
  if (process.argv.includes('--check')) {
    if (current !== next) {
      console.error('scripts/upstream-snapshot/client.patch is stale; run `npm run upstream:patch`');
      process.exit(1);
    }
    console.log('client.patch is up to date.');
  } else {
    fs.writeFileSync(clientPatchFile, next);
    console.log(`client.patch regenerated (${forkedFiles.length} files).`);
  }
}
